from rdflib import Graph, Namespace, RDF, URIRef, Literal

SH = Namespace("http://www.w3.org/ns/shacl#")
ODRL = Namespace("http://www.w3.org/ns/odrl/2/")


def explain_SHACL_validation_report(report_graph: Graph) -> str:
    """
    Convert a pySHACL validation report RDF graph into a short,
    human-readable explanation.

    Example output:

    SHACL validation failed with 2 violations.

    - Action error: A rule has more than one action (play, stream).
      Only one action is allowed.

    - Target error: A rule has more than one target (1999.mp3,
      PurpleRain.mp3). Only one target is allowed.
    """

    results = list(report_graph.objects(None, SH.result))

    if not results:
        conforms = list(report_graph.objects(None, SH.conforms))

        if conforms and str(conforms[0]).lower() == "true":
            return "SHACL validation passed. No violations were found."

        return "SHACL validation failed, but no detailed violations were found."

    # Count severities
    severity_counts = {}

    for result in results:
        severity = report_graph.value(result, SH.resultSeverity)

        if severity:
            severity_name = _shacl_term_label(severity)
        else:
            severity_name = "Violation"

        severity_counts[severity_name] = severity_counts.get(
            severity_name, 0
        ) + 1

    summary_parts = []
    for severity, count in severity_counts.items():
        noun = "issue" if count == 1 else "issues"
        summary_parts.append(f"{count} {severity.lower()} {noun}")

    lines = [
        "SHACL validation failed with "
        + ", ".join(summary_parts)
        + ".",
        ""
    ]

    for result in results:
        severity = report_graph.value(result, SH.resultSeverity)
        path = report_graph.value(result, SH.resultPath)
        message = report_graph.value(result, SH.resultMessage)
        focus_node = report_graph.value(result, SH.focusNode)

        severity_label = (
            _shacl_term_label(severity)
            if severity
            else "Violation"
        )

        path_label = _shacl_path_label(path)

        # Prefer pySHACL's message because it usually already explains
        # the actual constraint violation.
        explanation = _make_human_shacl_message(
            report_graph,
            result,
            path,
            message
        )

        lines.append(
            f"- {path_label} {severity_label.lower()}: {explanation}"
        )

        # Only include the focus node when it can be expressed simply.
        focus_label = _simple_node_label(focus_node)

        if focus_label:
            lines.append(f"  Affected rule: {focus_label}")

        lines.append("")

    return "\n".join(lines).strip()


def _make_human_shacl_message(
    report_graph: Graph,
    result,
    path,
    message
) -> str:
    """
    Turn common SHACL messages generated by pySHACL into more natural
    human-readable messages.
    """

    raw_message = str(message) if message else ""

    # MaxCountConstraintComponent
    source_constraint = report_graph.value(
        result,
        SH.sourceConstraintComponent
    )

    if source_constraint == SH.MaxCountConstraintComponent:
        count = report_graph.value(result, SH.sourceShape)

        # Get the maximum allowed count from the source shape.
        max_count = None

        if count:
            max_count = report_graph.value(count, SH.maxCount)

        if max_count is not None:
            values = _get_path_values(report_graph, result, path)

            value_text = _format_values(values)

            if value_text:
                return (
                    f"This rule has more than {max_count} "
                    f"{_shacl_path_label(path).lower()} "
                    f"({value_text}). "
                    f"Only {max_count} is allowed."
                )

            return (
                f"This rule has more than {max_count} "
                f"{_shacl_path_label(path).lower()}. "
                f"Only {max_count} is allowed."
            )

    # MinCountConstraintComponent
    if source_constraint == SH.MinCountConstraintComponent:
        source_shape = report_graph.value(result, SH.sourceShape)
        min_count = (
            report_graph.value(source_shape, SH.minCount)
            if source_shape
            else None
        )

        if min_count is not None:
            return (
                f"This rule is missing its required "
                f"{_shacl_path_label(path).lower()}. "
                f"At least {min_count} is required."
            )

    # ClassConstraintComponent
    if source_constraint == SH.ClassConstraintComponent:
        return (
            f"The value of {_shacl_path_label(path).lower()} "
            f"does not have the required type."
        )

    # DatatypeConstraintComponent
    if source_constraint == SH.DatatypeConstraintComponent:
        return (
            f"The value of {_shacl_path_label(path).lower()} "
            f"has an invalid datatype."
        )

    # NodeKindConstraintComponent
    if source_constraint == SH.NodeKindConstraintComponent:
        return (
            f"The value of {_shacl_path_label(path).lower()} "
            f"has an invalid RDF node type."
        )

    # Fallback: clean up pySHACL's original message.
    if raw_message:
        return _clean_shacl_message(raw_message)

    return "This rule does not satisfy the required constraint."


def _get_path_values(report_graph: Graph, result, path):
    """
    Find the actual values responsible for the violation.

    pySHACL reports the focus node but not always the values directly,
    so follow the reported property path.
    """

    focus_node = report_graph.value(result, SH.focusNode)

    if not focus_node or not path:
        return []

    # Normal property path, e.g. odrl:action or odrl:target
    if isinstance(path, URIRef):
        return list(report_graph.objects(focus_node, path))

    return []


def _format_values(values):
    """
    Convert RDF values into a compact human-readable list.
    """

    labels = []

    for value in values:
        label = _simple_node_label(value)

        if label:
            labels.append(label)

    if not labels:
        return ""

    if len(labels) == 1:
        return labels[0]

    if len(labels) == 2:
        return f"{labels[0]} and {labels[1]}"

    return ", ".join(labels[:-1]) + f", and {labels[-1]}"


def _simple_node_label(node):
    """
    Produce a short readable representation of an RDF node.
    """

    if node is None:
        return ""

    if isinstance(node, Literal):
        return str(node)

    if isinstance(node, URIRef):
        uri = str(node)

        # ODRL terms
        if uri.startswith(str(ODRL)):
            return uri[len(str(ODRL)):]

        # Fragment identifiers
        if "#" in uri:
            return uri.rsplit("#", 1)[1]

        # Last part of an HTTP URI
        if "/" in uri:
            return uri.rstrip("/").rsplit("/", 1)[1]

        return uri

    return str(node)


def _shacl_term_label(term):
    """
    Convert SHACL vocabulary terms into readable names.
    """

    if term is None:
        return ""

    text = str(term)

    if text.startswith(str(SH)):
        text = text[len(str(SH)):]

    return text.replace("ConstraintComponent", "").replace("_", " ")


def _shacl_path_label(path):
    """
    Convert an RDF predicate/path into a readable property name.
    """

    if path is None:
        return "Constraint"

    label = _simple_node_label(path)

    if not label:
        return "Constraint"

    # ODRL properties are generally already readable:
    # odrl:action -> Action
    # odrl:target -> Target
    return label.replace("_", " ").capitalize()


def _clean_shacl_message(message):
    """
    Clean up common pySHACL wording when no specialised explanation
    is available.
    """

    message = message.strip()

    # pySHACL often produces:
    # "More than 1 values on ...->odrl:action"
    if message.startswith("More than ") and " values on " in message:
        return message.replace(
            "More than ",
            "This rule has more than ",
            1
        ).replace(
            " values on ",
            " value(s) for ",
            1
        ) + "."

    return message